name: Laravel CI

on:
  push:

jobs:
  # lesson1-hello:
  #   runs-on: ubuntu-latest

    # steps:
    #   - name: Say hello
    #     run: echo "Hello Github Actions"
      
    #   - name: Show current directory
    #     run: pwd

    #   - name: List files
    #     run: ls -la
      
    #   - name: Show PHP version
    #     run: php -v
      
    #   - name: Show Composer version
    #     run: composer --version

  # lesson2-checkout-code:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Show files before checkout
  #       run: ls -la

  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Show files after checkout
  #       run: ls -la
  lesson3-setup-php-composer-and-run-laravel:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel_test
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Create env file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
  
