name: Test SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            whoami
            hostname
            pwd